name: remote ssh command
on: 
  push:
    branches: [ main ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing gitaction for ssh
        script: |
          ssh majid@103.83.89.237 -p 8010 "mkdir majid-gitaction"
