name: remote ssh command
on: 
  push:
    branches: [ main ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing gitaction for ssh
      uses: appleboy/ssh-action@master
      with:
        host: 103.83.89.237
        username: majid
        key: ${{ SSH_KEY }}
        port: 8010
        script: |
          sh mkdir.sh
