# This is a basic workflow to help you get started with Actions

name: Deploy on local

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
jobs:
   job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: testing ssh
         uses: appleboy/ssh-action@master
         with:
           host: 103.83.89.237
           username: majid
           key: ${{ MAJID_SSH_KEY }}
           port: 8010
           script:
             cd /home/majid/gitaction
             git pull origin master
             git status
