on:
  push:
    branches:
      - main
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} -p 8010 > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh root@103.83.89.237 -p 8010 "cd /root/nginx-image && mkdir asimtest"
    - name: cleanup
      run: rm -rf ~/.ssh
