name: Deploy on local
on:
  push:
    branches: ["main"]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testing ssh
        uses: appleboy/ssh-action@master
        with:
          host: 103.83.89.237
          username: majid
          key: ${{ SECRETS_PRIVATE_KEY }}
          port: 8010
          script: cd /home/majid/gitaction
            git pull https://github.com/minayyar/gitaction.git
          
